### ISSUE TITLE
Legend not drawing correctly with Direct2D support

### ISSUE THREAD

**Issue by darrenwwilliams** [mity/mctrl#38]
After building mCtrl 0.9.7 I notice that the chart legend is not drawing correctly with Direct 2D while the old GDI methods are working fine. It seems like there is a calculation error in the positioning under Direct 2D. I haven't had a chance to look at the methods yet but I thought I would log this first.

It also appears not to redraw in the same way as GDI and keep the aspect ratio the same.

**Comment by mity** [comment]
Can you post some screenshot here? What's your Windows version? What's your DPI setting?

**Comment by darrenwwilliams** [comment]
Sure.

This is on Windows 7.

This is with GDI+



Same app with Direct2\. Note the Font size firstly and then when i roll over the pie I note thither is something trying to be drawn in the top right. As shown in the 3rd screen shot. I am using windows 7 under a VMWARE virtual machine.DPI setting is at 96 as shown in 4th screen shot.









cheers, darren



________________________
Darren Williams, Ph.D.

**Comment by mity** [comment]
The screenshots were not propagated from your e-mail. They should be possible to add by simple drag&drop when writing a comment on https://github.com/mity/mctrl/issues/38.

**Comment by mity** [comment]
I tried to reproduce with the `ex_chart.exe` example on a notebook with Windows 7, but everything seems ok to me. 

Can you check whether you can reproduce with the example, or if it only happens in your app? If the latter, can you perhaps create some minimal example and provide its code?

**Comment by darrenwwilliams** [comment]
Sure. I will try this in the morning to confirm.

Thanks Darren

**Comment by darrenwwilliams** [comment]
Can you please send me your private email so i can send you a sample project. 

cheers, Darren
________________________
Darren Williams, Ph.D.

**Comment by mity** [comment]
I don't want to provide too openly on web to minimize spam. You can find it in file `AUTHORS` in the distribution of mCtrl (source as well as binary).

**Comment by darrenwwilliams** [comment]
Thanks

**Comment by mity** [comment]
Ok, so after some debugging session, I've actually found two independent bugs:

1. DirectWrite/Direct2D does not like the font collection `"SYSTEM"`, which is unfortunately default in Win32 due the old the legacy compatibility. This caused that font metrics structure was left uninitialized and it caused issues when computing legend layout. Fixed (well, worked-around is more appropriate word here) in 1a5d451cc1e02d7cc4fbd0432cd15e1ec6463f33.

(Workaround for mCtrl 0.9.7 is to set any true-type font via `WM_SETFONT` to the control.)

2. `WM_SIZE` was not handled properly so Direct2D rescaled the output to new control size instead of recalculating the layout and repainting. Fixed in 08b1adc232bb7a49fe4f60b2b5d8515dac81ee29.

Thanks for reporting this.
