### ISSUE TITLE
[Grid] InvalidateRect flicker

### ISSUE THREAD

**Issue by Bugzero71** [mity/mctrl#45]
When I need to notify grid control that some values in view have changed I call:

```cpp
::InvalidateRect(hwnd, NULL, FALSE);
```

I see a flicker effect in control. Is there a different way to tell the control to resend all MC_GN_GETDISPINFOW messages again?

**Comment by mity** [comment]
If you need to update just few cells, you might try to invalidate just those. See `MC_GM_GETCELLRECT`.
If it does not help, `MC_GS_DOUBLEBUFFER` should do.

**Comment by Bugzero71** [comment]
OK I will test it

**Comment by Bugzero71** [comment]
MC_GS_DOUBLEBUFFER has some problems redrawing elements when scrolling. Have you tested it?
I will try to cache all element values to detect which of them have changed and send InvalidateRect only to the ones that have changed.

**Comment by Bugzero71** [comment]
I see MC_GS_DOUBLEBUFFER works perfectly well when moving with keyboard keys (arrows and page up/down). When I use a mouse to scroll both with scroll bar or with mouse wheel some elements are not repainted.

**Comment by mity** [comment]
> Have you tested it?

Likely not with scrolling while small area is invalid. I mostly test just with the example and this simply is not currently covered.

**Comment by Bugzero71** [comment]
Martin, I don't want to bother you if you have too much work.
If you want I can help you improve Grid and TreeList controls as I need them in a project at work. I know I need some strange things but I'm implementing a debugger and I need fast controls to show a lots of informations.

**Comment by mity** [comment]
Well, I of course want to have mCtrl as good as possible so I see fixing those issues as an important thing. It's just a matter of time. Of course, helping in that is always welcome, where help may be anything of 

 * providing a patch (ideally pull request) fixing the issue.
 * providing a code which can be used to reproduce/test, ideally in the form of new example or by extending a current one if its not too against its nature (well the example should ideally focus on some coherent set of control features and they should not be overly complicated by combining everything in the same place.)
 * reporting the bugs.

In some longer term, I would like to see some better unit testing involved (some rudimentary work has been started in the `tests` dir but it is just start. Ideally everything what can be tested automatically should be eventually there. But again it's the matter of priorities and time.

**Comment by Bugzero71** [comment]
So Martin if you want I can prepare examples in pure C to test both *GETDISPINFO messages on Grid and on TreeList using MC_LPSTR_TEXTCALLBACK so we can improve them

**Comment by mity** [comment]
That would helpful.

Anyway I played with it a little bit, and I can see there are multiple issues with Grid painting. 

 * `grid_paint()` always paints more or less all client area, not just the cells in the dirty area. That's pretty bad and may cause a lot of the flickering.
 * There are some issues with double-buffering when just some rectangle, not  a whole client area, is invalidated. It's likely what has bit you in the scrolling, although the scrolling itself is just trigger of the conditions, not the real cause.

I'll try to take a look at those issues in the upcoming days.

**Comment by mity** [comment]
`grid_paint()` should now be fixed and paint only needed cells.

The other problem with double-buffering is some conflict of clipping and painting into a memory bitmap whose origin [0,0] corresponds to other point on the window. My theory is that `SelectClipRgn()` does not look at DC's origin as set by e.g. `OffsetViewportOrgEx()` or `SetViewportOrgEx()`.

Unfortunately docs for those function on MSDN does not much explain whether the clipping functions use physical or logical coordinate system...

I need a fresh mind before I look at that more closely but at least I think I am on the right track.

**Comment by mity** [comment]
Finally, I got it, I think.

With double-buffering, we may paint into a bitmap whose [0,0] does not correspond to [0,0] of the control's client area. It happens whenever the invalid region covers just part of the window more to the right and/or to the bottom.

On newer systems (>= Vista), the double-buffering is based on `BeginBufferedPaint()` which internally calls `SetWindowOrgEx()` to make the compensation.

On older systems, we used our own implementation allocating compatible bitmap manually, and calling `SetViewportOrgEx()` to make the compensation.

And finally, when clipping got into the game, and we called `mc_clip_set()` based on `SelectClipRgn()`, we got into issue, because this function apparently uses physical coordinate system ignoring the compensation.

So I unified the code for older systems to use `SetWindowOrgEx()` as well, and make  `mc_clip_set()` to compensate manually. It now seems to work correctly to me with and without the double-buffering.

Tested on Win 2000 and Win 10 with modified `example-grid.exe` which updated contents of a cell many times per second (and invalidating just the single cell). I don't want to commit that as it was just a quick hack though and it does not make nice code for an example.

**Comment by mity** [comment]
(Just cannot understand how this serious issue escaped my radar for so long...)

**Comment by Bugzero71** [comment]
Probably nobody needed it and you tested it in a small grid.

**Comment by Bugzero71** [comment]
Double buffering is working fine now.
