### ISSUE TITLE
isolation awareness support

### ISSUE THREAD

**Issue by namazso** [mity/mctrl#89]
not sure if this is more of a "bug" or a feature request, but when compiling with ISOLATION_AWARE_ENABLED (well, officially there is no option for this so I guess it's more like my fault) this assertation will fail:
https://github.com/mity/mctrl/blob/master/src/misc.c#L744
because enabling isolation awareness makes it not link against comctl32.dll. an easy fix would be simply calling `InitCommonControlsEx(NULL)` before to get it load comctl32, although this relies on the undocumented feature that this call safely fails when passed nullptr. Another way to fail it is setting dwSize to 0.

**Comment by mity** [comment]
I have only vague knowledge about the isolation support in Windows so maybe I am wrong. But isn't compiling mCtrl with `ISOLATION_AWARE_ENABLED` meaningless unless all exported function calls (and probably also all control window procedures) would be wrapped in calls of `ActivateActCtx()` and `DeactivateActCtx()`?

Also we would have to specify exact versions of system DLLs we depend on in the DLL's manifest: But we generally want to use the latest available, sometimes trying to get functions available only in newer DLL versions via `GetProcAddress()`. (Well, not that much since ripping out support for old Windows version < Windows Vista, but still there are some cases.)

**Comment by namazso** [comment]
Right, I really just stumbled into this while using mCtrl as a static library in my isolation-requiring dll by copypasting an example for test. On a second thought this is dumb or maybe wrong for the "normal" usage, and I already solved it for myself by simply swapping order of InitCommonControlsEx and mcInitialize.
